// Step 12: Create README.md, STRUCTURE.md, .claude/napkin.md if missing.
// Skip if exists + non-empty (never overwrite customer content).

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { atomicWriteFile } from '../atomic-write.js';

import type { StepFn } from './types.js';

interface SeedFile {
  relativePath: string;
  content: string;
}

function seeds(companyName: string): SeedFile[] {
  return [
    {
      relativePath: 'README.md',
      content: [
        `# ${companyName} — mySecond PM Operating System`,
        '',
        'This workspace is your mySecond PM OS. Context files in `context/`',
        'are auto-loaded into Claude Code at session start; skills and agents',
        'live under `.claude/`.',
        '',
        '## Try it',
        '',
        '- `/prd-generator` — draft a PRD from a vague idea',
        '- `/skills` — see everything available',
        '- `/enhance-context` — upload research, interview notes, strategy docs',
        '',
        'Sync runs automatically on every Claude Code session. To force-sync,',
        'run `mysecond sync` from this directory.',
      ].join('\n') + '\n',
    },
    {
      relativePath: 'STRUCTURE.md',
      content: [
        '# Workspace structure',
        '',
        '- `context/` — company / product / personas / competitors (auto-loaded into Claude via `@import` in CLAUDE.md)',
        '- `.claude/skills/` — installed skills (synced from mysecond.ai)',
        '- `.claude/agents/` — installed agents',
        '- `workflows/` — installed workflows',
        '- `.claude/sync-state.json` — local sync ledger (don\'t edit by hand)',
        '- `.claude/napkin.md` — your scratchpad (corrections, preferences, ongoing notes)',
        '',
        'Generated by `mysecond init`. Safe to edit any of the above; mySecond never overwrites customer-authored content.',
      ].join('\n') + '\n',
    },
    {
      relativePath: '.claude/napkin.md',
      content: [
        '# Napkin',
        '',
        'Your scratchpad. mySecond skills read this so they remember corrections,',
        'preferences, and patterns across sessions. Edit freely.',
        '',
        '## Corrections',
        '',
        '_(Add things you\'ve had to correct repeatedly — Claude will avoid them next time.)_',
        '',
        '## Preferences',
        '',
        '_(How you like to work, formatting choices, terminology.)_',
        '',
        '## Active context',
        '',
        '_(What you\'re working on right now.)_',
      ].join('\n') + '\n',
    },
  ];
}

export const step12: StepFn = async ({ ctx, shared }) => {
  // RED-TEAM R2 P0-A: companyName is now a separate shared field. v1 used
  // shared.customerName for both PM + company; that conflation produced
  // "for [PM] at [PM]" in the success box. step-12 doesn't need pmName but
  // does use companyName as the README header.
  const companyName = shared.companyName ?? 'Your company';
  for (const seed of seeds(companyName)) {
    const fullPath = join(ctx.rootDir, seed.relativePath);
    if (existsSync(fullPath)) {
      const existing = readFileSync(fullPath, 'utf8').trim();
      if (existing.length > 0) continue; // never overwrite non-empty customer content
    }
    atomicWriteFile(fullPath, seed.content, { mkdirRecursive: true });
  }
  return { step: 12, outcome: { kind: 'completed' } };
};
